
    upstream vistcount_app {
     server webapp:5000; #Webapp port; also exists in the Flask directory's Docker image.
    }

    server {
        listen 80;

        location / {
            proxy_pass http://vistcount_app;
        }
    }
