FROM ubuntu:20.04 AS BuilderStage

WORKDIR /app

RUN apt-get update && apt-get install -y \
 --no-install-recommends \ 
ca-certificates \ 
wget \ 
dpkg-dev \ 
gcc \  
g++ \
libc6-dev \
libssl-dev \
make \
git \
python3 \
python3-pip \
python3-venv \
python3-dev \
 unzip \
 rsync \
 clang \
automake \
 autoconf \
 gcc-10 \
 g++-10\
 libtool\
&& rm -rf /var/lib/apt/lists/*

RUN  update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10

RUN pip3 install cmake==3.31.6 &&\
ln -sf /usr/local/bin/cmake /usr/bin/cmake \
cmake --version

RUN wget -O redis-8.0.0.tar.gz https://github.com/redis/redis/archive/refs/tags/8.0.0.tar.gz

RUN tar xvf redis-8.0.0.tar.gz && \
rm redis-8.0.0.tar.gz

WORKDIR /app/redis-8.0.0

RUN export BUILD_TLS=yes BUILD_WITH_MODULES=yes INSTALL_RUST_TOOLCHAIN=yes DISABLE_WERRORS=yes && \
make -j "$(nproc)" all

FROM ubuntu:20.04 AS ProductionStage

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libssl1.1 \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY --from=BuilderStage /app/redis-8.0.0/src/redis-server /app/redis-server

EXPOSE 6379

CMD [ "./redis-server"]

